---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "offsite26.fullname" . }}
  labels:
    app: {{ template "offsite26.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment }}
    namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: "{{ $key }}"
      port: {{ $value.port }}
      protocol: {{ $value.protocol }}
      targetPort: {{ $value.targetPort }}
    {{- end }}
  selector:
    app: {{ template "offsite26.name" . }}
    release: {{ .Release.Name }}
